server:
  port: 8090

spring:
  profiles:
    active: dev
  application:
    name: service-mail #服务名
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 81.68.222.35
    port: 6379
    database: 0
    password:  #默认为空
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

  # 发送邮箱的主体smtp设置
  mail:
    host: smtp.qq.com         #发送邮件服务器
    username:  791533056@qq.com   #邮箱
    password:  zggymzqlmdqtbdbd   #客户端授权码
    subject: 注册验证码 # 邮件主题
    properties.mail.smtp.port: 465
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

  freemarker:
    cache: false # 缓存配置 开发阶段应该配置为false 因为经常会改
    suffix: .html # 模版后缀名 默认为ftl
    charset: UTF-8 # 文件编码
    template-loader-path: classpath:/templates/  # 存放模板的文件夹，以resource文件夹为相对路径

